version: '3.1'
services:
  client-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: client-app
    image: client-app 
    restart: always
    ports:
      - "5000:80"

  php-api:
    build:
      context: /home/mosad/app-dev/client
      dockerfile: Dockerfile
    image: php-api
    container_name: php-api
    restart: unless-stopped
    tty: true
    environment:
            - 'DB_PORT=3306'
            - 'DB_HOST=mysql'
    depends_on:
      - db
     
 
  db:
    image: mysql:latest
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bookapi
      MYSQL_USERNAME: app 
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql   
